import { countryCodeToFlag } from '@/lib/airports';

/** Map from full country name to ISO 3166-1 alpha-2 code. */
export const COUNTRY_NAME_TO_CODE: Record<string, string> = {
  'Kingdom of the Netherlands': 'NL',
  'Netherlands': 'NL',
  'Germany': 'DE',
  'France': 'FR',
  'United Kingdom': 'GB',
  'United States': 'US',
  'Spain': 'ES',
  'Italy': 'IT',
  'Belgium': 'BE',
  'Switzerland': 'CH',
  'Turkey': 'TR',
  'Norway': 'NO',
  'Sweden': 'SE',
  'Denmark': 'DK',
  'Ireland': 'IE',
  'Portugal': 'PT',
  'Austria': 'AT',
  'Poland': 'PL',
  'Greece': 'GR',
  'Finland': 'FI',
  'Czech Republic': 'CZ',
  'Czechia': 'CZ',
  'Romania': 'RO',
  'Hungary': 'HU',
  'Luxembourg': 'LU',
  'Iceland': 'IS',
  'Canada': 'CA',
  'China': 'CN',
  'Japan': 'JP',
  'South Korea': 'KR',
  'Australia': 'AU',
  'Brazil': 'BR',
  'India': 'IN',
  'Russia': 'RU',
  'Saudi Arabia': 'SA',
  'United Arab Emirates': 'AE',
  'Israel': 'IL',
  'Mexico': 'MX',
  'Singapore': 'SG',
  'Thailand': 'TH',
  'Indonesia': 'ID',
  'Malaysia': 'MY',
  'South Africa': 'ZA',
  'Argentina': 'AR',
  'Colombia': 'CO',
  'Egypt': 'EG',
  'Morocco': 'MA',
  'Qatar': 'QA',
  'Kuwait': 'KW',
  'Oman': 'OM',
  'Bahrain': 'BH',
  'Ethiopia': 'ET',
  'Kenya': 'KE',
  'Nigeria': 'NG',
  'Taiwan': 'TW',
  'Philippines': 'PH',
  'Vietnam': 'VN',
  'New Zealand': 'NZ',
  'Croatia': 'HR',
  'Bulgaria': 'BG',
  'Serbia': 'RS',
  'Ukraine': 'UA',
  'Lithuania': 'LT',
  'Latvia': 'LV',
  'Estonia': 'EE',
  'Slovakia': 'SK',
  'Slovenia': 'SI',
  'Malta': 'MT',
  'Cyprus': 'CY',
};

/** Convert a full country name to its flag emoji, or null if unmapped. */
export function countryNameToFlag(countryName: string): string | null {
  const code = COUNTRY_NAME_TO_CODE[countryName];
  if (!code) return null;
  return countryCodeToFlag(code);
}
