CREATE TABLE "ingest"."adsblol_state_vectors" (
	"id" bigserial PRIMARY KEY NOT NULL,
	"poll_id" uuid NOT NULL,
	"polled_at" timestamp with time zone DEFAULT now() NOT NULL,
	"response_time_ms" bigint NOT NULL,
	"icao24" text NOT NULL,
	"flight" text,
	"registration" text,
	"aircraft_type" text,
	"source_type" text,
	"latitude" double precision,
	"longitude" double precision,
	"altitude_baro" double precision,
	"altitude_geom" double precision,
	"ground_speed" double precision,
	"indicated_air_speed" double precision,
	"true_air_speed" double precision,
	"mach" double precision,
	"track" double precision,
	"track_rate" double precision,
	"roll" double precision,
	"magnetic_heading" double precision,
	"true_heading" double precision,
	"baro_rate" double precision,
	"geom_rate" double precision,
	"squawk" text,
	"emergency" text,
	"category" text,
	"nav_qnh" double precision,
	"nav_altitude_mcp" integer,
	"nav_altitude_fms" integer,
	"nav_heading" double precision,
	"nav_modes" jsonb,
	"nic" smallint,
	"rc" integer,
	"seen" real,
	"seen_pos" real,
	"version" smallint,
	"nic_baro" smallint,
	"nac_p" smallint,
	"nac_v" smallint,
	"sil" smallint,
	"sil_type" text,
	"gva" smallint,
	"sda" smallint,
	"alert" boolean,
	"spi" boolean,
	"messages" integer,
	"rssi" real,
	"distance" real,
	"direction" real,
	"raw" jsonb NOT NULL
);
--> statement-breakpoint
CREATE INDEX "idx_alsv_polled_at" ON "ingest"."adsblol_state_vectors" USING btree ("polled_at");--> statement-breakpoint
CREATE INDEX "idx_alsv_icao24" ON "ingest"."adsblol_state_vectors" USING btree ("icao24");--> statement-breakpoint
CREATE INDEX "idx_alsv_icao24_polled_at" ON "ingest"."adsblol_state_vectors" USING btree ("icao24","polled_at");