import {
  pgSchema,
  bigserial,
  bigint,
  boolean,
  doublePrecision,
  index,
  integer,
  jsonb,
  real,
  smallint,
  text,
  timestamp,
  uuid,
} from 'drizzle-orm/pg-core';

export const ingestSchema = pgSchema('ingest');

export const openskyStateVectors = ingestSchema.table(
  'opensky_state_vectors',
  {
    id: bigserial({ mode: 'number' }).primaryKey(),
    pollId: uuid('poll_id').notNull(),
    polledAt: timestamp('polled_at', { withTimezone: true }).notNull().defaultNow(),
    responseTime: integer('response_time').notNull(),
    icao24: text('icao24').notNull(),
    callsign: text('callsign'),
    originCountry: text('origin_country'),
    timePosition: integer('time_position'),
    lastContact: integer('last_contact'),
    longitude: doublePrecision('longitude'),
    latitude: doublePrecision('latitude'),
    baroAltitude: doublePrecision('baro_altitude'),
    onGround: boolean('on_ground'),
    velocity: doublePrecision('velocity'),
    trueTrack: doublePrecision('true_track'),
    verticalRate: doublePrecision('vertical_rate'),
    sensors: jsonb('sensors').$type<readonly number[] | null>(),
    geoAltitude: doublePrecision('geo_altitude'),
    squawk: text('squawk'),
    spi: boolean('spi'),
    positionSource: smallint('position_source'),
  },
  (table) => [
    index('idx_osv_polled_at').on(table.polledAt),
    index('idx_osv_icao24').on(table.icao24),
    index('idx_osv_icao24_polled_at').on(table.icao24, table.polledAt),
  ],
);

export const metar = ingestSchema.table(
  'metar',
  {
    id: bigserial({ mode: 'number' }).primaryKey(),
    fetchedAt: timestamp('fetched_at', { withTimezone: true }).notNull().defaultNow(),
    station: text('station').notNull(),
    raw: text('raw').notNull(),
    observationTime: timestamp('observation_time', { withTimezone: true }),
    temp: real('temp'),
    dewpoint: real('dewpoint'),
    windDirection: smallint('wind_direction'),
    windSpeed: smallint('wind_speed'),
    windGust: smallint('wind_gust'),
    visibility: real('visibility'),
    clouds: jsonb('clouds').$type<readonly { cover: string; base: number }[] | null>(),
    ceiling: integer('ceiling'),
    qnh: real('qnh'),
    flightCategory: text('flight_category'),
  },
  (table) => [index('idx_metar_fetched_at').on(table.fetchedAt)],
);

export const flightyArrivals = ingestSchema.table(
  'flighty_arrivals',
  {
    id: bigserial({ mode: 'number' }).primaryKey(),
    scrapedAt: timestamp('scraped_at', { withTimezone: true }).notNull().defaultNow(),
    flightId: text('flight_id').notNull(),
    flightNumber: text('flight_number').notNull(),
    airlineIata: text('airline_iata'),
    airlineName: text('airline_name'),
    city: text('city'),
    status: jsonb('status'),
    originalTime: jsonb('original_time'),
    newTime: jsonb('new_time'),
    departure: jsonb('departure'),
    arrival: jsonb('arrival'),
    secondaryCorner: text('secondary_corner'),
  },
  (table) => [
    index('idx_fa_scraped_at').on(table.scrapedAt),
    index('idx_fa_flight_number').on(table.flightNumber),
  ],
);

export const openskyTracks = ingestSchema.table(
  'opensky_tracks',
  {
    id: bigserial({ mode: 'number' }).primaryKey(),
    fetchedAt: timestamp('fetched_at', { withTimezone: true }).notNull().defaultNow(),
    icao24: text('icao24').notNull(),
    requestedTime: integer('requested_time').notNull(),
    startTime: integer('start_time'),
    endTime: integer('end_time'),
    callsign: text('callsign'),
    path: jsonb('path').$type<
      readonly [
        number,
        number | null,
        number | null,
        number | null,
        number | null,
        boolean,
      ][]
    | null>(),
    source: text('source').notNull().default('state_vectors'),
  },
  (table) => [
    index('idx_ost_icao24').on(table.icao24),
    index('idx_ost_fetched_at').on(table.fetchedAt),
    index('idx_ost_icao24_requested_time').on(table.icao24, table.requestedTime),
  ],
);

export const adsblolStateVectors = ingestSchema.table(
  'adsblol_state_vectors',
  {
    id: bigserial({ mode: 'number' }).primaryKey(),
    pollId: uuid('poll_id').notNull(),
    polledAt: timestamp('polled_at', { withTimezone: true }).notNull().defaultNow(),
    responseTimeMs: bigint('response_time_ms', { mode: 'number' }).notNull(),
    icao24: text('icao24').notNull(),
    flight: text('flight'),
    registration: text('registration'),
    aircraftType: text('aircraft_type'),
    sourceType: text('source_type'),
    latitude: doublePrecision('latitude'),
    longitude: doublePrecision('longitude'),
    altitudeBaro: doublePrecision('altitude_baro'),
    altitudeGeom: doublePrecision('altitude_geom'),
    groundSpeed: doublePrecision('ground_speed'),
    indicatedAirSpeed: doublePrecision('indicated_air_speed'),
    trueAirSpeed: doublePrecision('true_air_speed'),
    mach: doublePrecision('mach'),
    track: doublePrecision('track'),
    trackRate: doublePrecision('track_rate'),
    roll: doublePrecision('roll'),
    magneticHeading: doublePrecision('magnetic_heading'),
    trueHeading: doublePrecision('true_heading'),
    baroRate: doublePrecision('baro_rate'),
    geomRate: doublePrecision('geom_rate'),
    squawk: text('squawk'),
    emergency: text('emergency'),
    category: text('category'),
    navQnh: doublePrecision('nav_qnh'),
    navAltitudeMcp: integer('nav_altitude_mcp'),
    navAltitudeFms: integer('nav_altitude_fms'),
    navHeading: doublePrecision('nav_heading'),
    navModes: jsonb('nav_modes').$type<readonly string[] | null>(),
    nic: smallint('nic'),
    rc: integer('rc'),
    seen: real('seen'),
    seenPos: real('seen_pos'),
    version: smallint('version'),
    nicBaro: smallint('nic_baro'),
    nacP: smallint('nac_p'),
    nacV: smallint('nac_v'),
    sil: smallint('sil'),
    silType: text('sil_type'),
    gva: smallint('gva'),
    sda: smallint('sda'),
    alert: boolean('alert'),
    spi: boolean('spi'),
    messages: integer('messages'),
    rssi: real('rssi'),
    distance: real('distance'),
    direction: real('direction'),
    raw: jsonb('raw').notNull(),
  },
  (table) => [
    index('idx_alsv_polled_at').on(table.polledAt),
    index('idx_alsv_icao24').on(table.icao24),
    index('idx_alsv_icao24_polled_at').on(table.icao24, table.polledAt),
  ],
);
